-- Generated from the app's demo data by scripts/generate-seed.ts
-- Run AFTER schema.sql in the Supabase SQL Editor.
-- Every row belongs to Account #1 ('acc_northwind').
insert into public.profiles (account_id, id, name, email, role, job_title, avatar_color) values
  ('acc_northwind', 'u-erik', 'Maya Visser', 'research.lead@example.com', 'admin', 'Head of UX Research', 'indigo'),
  ('acc_northwind', 'u-sanne', 'Sanne de Vries', 'sanne.devries@example.com', 'researcher', 'Senior UX Researcher', 'violet'),
  ('acc_northwind', 'u-tom', 'Tom Bakker', 'tom.bakker@example.com', 'researcher', 'UX Researcher', 'teal'),
  ('acc_northwind', 'u-julia', 'Julia Kowalski', 'julia.kowalski@example.com', 'designer', 'Product Designer', 'pink'),
  ('acc_northwind', 'u-marco', 'Marco Rossi', 'marco.rossi@example.com', 'product-owner', 'Product Owner, Mobile', 'amber'),
  ('acc_northwind', 'u-lena', 'Lena Fischer', 'lena.fischer@example.com', 'product-owner', 'Product Owner, Planning', 'green')
on conflict (id) do nothing;

insert into public.companies (account_id, id, name, industry, size, country, logo_accent) values
  ('acc_northwind', 'co-nordwind', 'Nordwind Energy', 'Utilities & Energy', '1001-5000', 'Germany', 'blue'),
  ('acc_northwind', 'co-valtech', 'ValTech Manufacturing', 'Discrete Manufacturing', '201-1000', 'Netherlands', 'orange'),
  ('acc_northwind', 'co-brightfoods', 'BrightFoods Group', 'Food & Beverage', '5000+', 'Belgium', 'green'),
  ('acc_northwind', 'co-riverside', 'Riverside Health', 'Healthcare Facilities', '1001-5000', 'United Kingdom', 'rose'),
  ('acc_northwind', 'co-portside', 'Portside Logistics', 'Logistics & Ports', '201-1000', 'Netherlands', 'cyan'),
  ('acc_northwind', 'co-alpine', 'Alpine Water Boards', 'Water Management', '51-200', 'Switzerland', 'teal'),
  ('acc_northwind', 'co-steelcore', 'SteelCore Industries', 'Heavy Industry', '5000+', 'Sweden', 'slate'),
  ('acc_northwind', 'co-lumen', 'Lumen Pharma', 'Pharmaceutical', '1001-5000', 'Ireland', 'purple')
on conflict (id) do nothing;

insert into public.personas (account_id, id, name, description, accent, icon) values
  ('acc_northwind', 'pe-technician', 'Maintenance Technician', 'Hands-on on the shop floor. Executes work orders, logs findings, and needs fast mobile access between jobs.', 'blue', 'Wrench'),
  ('acc_northwind', 'pe-planner', 'Maintenance Planner', 'Schedules preventive and corrective work, balances technician capacity, and keeps the backlog under control.', 'indigo', 'CalendarClock'),
  ('acc_northwind', 'pe-manager', 'Maintenance Manager', 'Owns team performance and maintenance KPIs. Lives in dashboards and reports to operations leadership.', 'violet', 'HardHat'),
  ('acc_northwind', 'pe-reliability', 'Reliability Engineer', 'Analyzes failure patterns, drives RCA, and optimizes maintenance strategy from asset history data.', 'teal', 'Gauge'),
  ('acc_northwind', 'pe-warehouse', 'Warehouse Employee', 'Manages spare parts stock, issues materials to work orders, and handles goods receipt.', 'amber', 'Warehouse'),
  ('acc_northwind', 'pe-purchaser', 'Purchaser', 'Converts requisitions to orders, manages suppliers, and tracks delivery of critical parts.', 'orange', 'ShoppingCart'),
  ('acc_northwind', 'pe-operations', 'Operations Manager', 'Owns plant uptime. Cares about how maintenance impacts production throughput and safety.', 'green', 'Factory'),
  ('acc_northwind', 'pe-asset', 'Asset Manager', 'Manages the asset register and lifecycle, capital planning, and long-term replacement strategy.', 'cyan', 'Boxes'),
  ('acc_northwind', 'pe-admin', 'Administrator', 'Configures the system, manages users and permissions, and maintains master data quality.', 'slate', 'ShieldCheck'),
  ('acc_northwind', 'pe-executive', 'Executive', 'C-level sponsor. Wants evidence that maintenance investments reduce risk and cost.', 'purple', 'Briefcase'),
  ('acc_northwind', 'pe-it', 'IT Manager', 'Responsible for integrations, security, SSO, and how the platform fits the enterprise landscape.', 'rose', 'Server')
on conflict (id) do nothing;

insert into public.tags (account_id, id, label, kind, accent) values
  ('acc_northwind', 'tag-early-adopter', 'Early Adopter', 'behaviour', 'green'),
  ('acc_northwind', 'tag-change-resistant', 'Change Resistant', 'behaviour', 'red'),
  ('acc_northwind', 'tag-analytical', 'Analytical', 'behaviour', 'indigo'),
  ('acc_northwind', 'tag-data-driven', 'Data Driven', 'behaviour', 'blue'),
  ('acc_northwind', 'tag-mobile-first', 'Mobile First', 'behaviour', 'cyan'),
  ('acc_northwind', 'tag-office-worker', 'Office Worker', 'behaviour', 'slate'),
  ('acc_northwind', 'tag-field-worker', 'Field Worker', 'behaviour', 'amber'),
  ('acc_northwind', 'tag-ai-enthusiast', 'AI Enthusiast', 'behaviour', 'violet'),
  ('acc_northwind', 'tag-pragmatic', 'Pragmatic', 'behaviour', 'teal'),
  ('acc_northwind', 'tag-power-user', 'Power User', 'behaviour', 'purple'),
  ('acc_northwind', 'tag-search', 'Search', 'pain-point', 'blue'),
  ('acc_northwind', 'tag-navigation', 'Navigation', 'pain-point', 'indigo'),
  ('acc_northwind', 'tag-reporting', 'Reporting', 'pain-point', 'violet'),
  ('acc_northwind', 'tag-planning', 'Planning', 'pain-point', 'purple'),
  ('acc_northwind', 'tag-work-orders', 'Work Orders', 'pain-point', 'orange'),
  ('acc_northwind', 'tag-mobile-experience', 'Mobile Experience', 'pain-point', 'cyan'),
  ('acc_northwind', 'tag-performance', 'Performance', 'pain-point', 'red'),
  ('acc_northwind', 'tag-dashboards', 'Dashboards', 'pain-point', 'teal'),
  ('acc_northwind', 'tag-notifications', 'Notifications', 'pain-point', 'amber'),
  ('acc_northwind', 'tag-integrations', 'Integrations', 'pain-point', 'rose'),
  ('acc_northwind', 'tag-ai', 'AI', 'pain-point', 'violet'),
  ('acc_northwind', 'tag-usability', 'Usability', 'pain-point', 'pink'),
  ('acc_northwind', 'tag-onboarding', 'Onboarding', 'pain-point', 'green'),
  ('acc_northwind', 'tag-data-quality', 'Data Quality', 'pain-point', 'lime'),
  ('acc_northwind', 'tag-quick-win', 'Quick Win', 'general', 'green'),
  ('acc_northwind', 'tag-needs-validation', 'Needs Validation', 'general', 'amber'),
  ('acc_northwind', 'tag-high-value', 'High Value', 'general', 'purple')
on conflict (id) do nothing;

insert into public.themes (account_id, id, name, description, accent) values
  ('acc_northwind', 'th-mobile-field', 'Mobile & Field Work', 'How technicians work away from a desk, offline, and on the move.', 'cyan'),
  ('acc_northwind', 'th-findability', 'Findability & Search', 'Locating assets, work orders, parts, and history quickly.', 'blue'),
  ('acc_northwind', 'th-planning-scheduling', 'Planning & Scheduling', 'Balancing capacity, backlog, and preventive vs. corrective work.', 'indigo'),
  ('acc_northwind', 'th-reporting-insight', 'Reporting & Insight', 'Turning maintenance data into decisions and KPIs.', 'violet'),
  ('acc_northwind', 'th-onboarding-learn', 'Onboarding & Learnability', 'How new users get productive and discover capabilities.', 'green'),
  ('acc_northwind', 'th-ai-assist', 'AI Assistance', 'Where AI can reduce manual effort and surface patterns.', 'purple'),
  ('acc_northwind', 'th-integration', 'Integrations & Ecosystem', 'Connecting to ERP, IoT, and the wider enterprise landscape.', 'rose'),
  ('acc_northwind', 'th-trust-data', 'Data Trust & Quality', 'Confidence in the accuracy and completeness of records.', 'lime')
on conflict (id) do nothing;

insert into public.participants (account_id, id, first_name, last_name, email, phone, avatar_color, company_id, department, job_title, country, language, timezone, industry, company_size, years_experience, seniority, responsibilities, daily_tasks, decision_influence, technical_proficiency, digital_maturity, products_used, modules_used, frequency, device, usage_level, persona_ids, behaviour_tag_ids, pain_point_tag_ids, consent_status, nda_signed, recording_permission, preferred_language, last_interview_date, interview_count, availability, recruitment_status, scheduled_session, notes) values
  ('acc_northwind', 'pt-lukas', 'Lukas', 'Brandt', 'l.brandt@nordwind-energy.de', '+49 30 5550 1122', 'blue', 'co-nordwind', 'Field Maintenance', 'Wind Turbine Technician', 'Germany', 'German', 'CET', 'Utilities & Energy', '1001-5000', 8, 'mid', array['Turbine inspections','Corrective repairs','Safety checks']::text[], array['Receive work orders on phone','Climb & inspect','Log findings','Order parts']::text[], 'low', 'intermediate', 'intermediate', array['Meridian EAM','Meridian Go (mobile)']::text[], array['Work Orders','Assets','Mobile']::text[], 'daily', 'field-mobile', 'intermediate', array['pe-technician']::text[], array['tag-field-worker','tag-mobile-first','tag-pragmatic']::text[], array['tag-mobile-experience','tag-search','tag-performance']::text[], 'granted', true, true, 'German', '2026-06-18', 3, 'Weekdays after 16:00 CET', 'interviewed', null, 'Great at articulating offline/connectivity struggles on turbines.'),
  ('acc_northwind', 'pt-fatima', 'Fatima', 'El Amrani', 'f.elamrani@valtech.nl', '+31 20 555 8890', 'indigo', 'co-valtech', 'Maintenance Planning', 'Maintenance Planner', 'Netherlands', 'Dutch', 'CET', 'Discrete Manufacturing', '201-1000', 12, 'senior', array['Weekly scheduling','Capacity balancing','Backlog grooming']::text[], array['Build schedules','Assign technicians','Chase overdue work orders']::text[], 'high', 'expert', 'expert', array['Meridian EAM']::text[], array['Planning','Work Orders','Reporting','Assets']::text[], 'daily', 'desktop', 'expert', array['pe-planner']::text[], array['tag-analytical','tag-power-user','tag-data-driven']::text[], array['tag-planning','tag-work-orders','tag-performance']::text[], 'granted', true, true, 'Dutch', '2026-06-25', 4, 'Tue/Thu mornings', 'interviewed', null, 'Power user — has strong opinions on the scheduling board.'),
  ('acc_northwind', 'pt-james', 'James', 'O''Connor', 'james.oconnor@riversidehealth.uk', null, 'violet', 'co-riverside', 'Estates & Facilities', 'Maintenance Manager', 'United Kingdom', 'English', 'GMT', 'Healthcare Facilities', '1001-5000', 18, 'lead', array['Team leadership','SLA compliance','Budget']::text[], array['Review KPIs','Approve work','Report to directors']::text[], 'high', 'intermediate', 'intermediate', array['Meridian EAM']::text[], array['Dashboards','Reporting','Work Orders']::text[], 'daily', 'both', 'intermediate', array['pe-manager']::text[], array['tag-data-driven','tag-office-worker']::text[], array['tag-dashboards','tag-reporting','tag-notifications']::text[], 'granted', true, true, 'English', '2026-06-11', 2, 'Fridays', 'interviewed', null, 'Compliance-driven; SLA reporting is his top concern.'),
  ('acc_northwind', 'pt-ingrid', 'Ingrid', 'Larsson', 'ingrid.larsson@steelcore.se', null, 'teal', 'co-steelcore', 'Reliability', 'Reliability Engineer', 'Sweden', 'Swedish', 'CET', 'Heavy Industry', '5000+', 10, 'senior', array['RCA','Failure analysis','Maintenance strategy']::text[], array['Analyze asset history','Run RCA','Tune PM intervals']::text[], 'high', 'expert', 'expert', array['Meridian EAM','Power BI']::text[], array['Assets','Reporting','Analytics']::text[], 'daily', 'desktop', 'expert', array['pe-reliability']::text[], array['tag-analytical','tag-data-driven','tag-ai-enthusiast']::text[], array['tag-reporting','tag-data-quality','tag-ai']::text[], 'granted', true, true, 'English', '2026-06-28', 2, 'Flexible remote', 'interviewed', null, 'Excited about AI-assisted failure pattern detection.'),
  ('acc_northwind', 'pt-piet', 'Piet', 'Jansen', 'p.jansen@portside.nl', null, 'cyan', 'co-portside', 'Terminal Maintenance', 'Crane Technician', 'Netherlands', 'Dutch', 'CET', 'Logistics & Ports', '201-1000', 22, 'senior', array['Crane upkeep','Breakdown response']::text[], array['Respond to breakdowns','Complete checklists']::text[], 'low', 'intermediate', 'beginner', array['Meridian EAM','Meridian Go (mobile)']::text[], array['Work Orders','Mobile']::text[], 'daily', 'field-mobile', 'beginner', array['pe-technician']::text[], array['tag-field-worker','tag-change-resistant']::text[], array['tag-usability','tag-mobile-experience','tag-onboarding']::text[], 'granted', false, true, 'Dutch', '2026-05-30', 1, 'Early mornings', 'interviewed', null, 'Veteran technician, skeptical of new tools — valuable counter-perspective.'),
  ('acc_northwind', 'pt-amara', 'Amara', 'Okafor', 'a.okafor@brightfoods.be', null, 'green', 'co-brightfoods', 'Operations', 'Plant Operations Manager', 'Belgium', 'English', 'CET', 'Food & Beverage', '5000+', 15, 'lead', array['Plant uptime','Production/maintenance coordination']::text[], array['Monitor OEE','Coordinate shutdowns','Escalations']::text[], 'high', 'intermediate', 'expert', array['Meridian EAM','SAP']::text[], array['Dashboards','Work Orders','Assets']::text[], 'weekly', 'both', 'intermediate', array['pe-operations']::text[], array['tag-data-driven','tag-analytical']::text[], array['tag-integrations','tag-dashboards','tag-notifications']::text[], 'granted', true, true, 'English', '2026-06-20', 2, 'Wednesdays', 'interviewed', null, 'Cares deeply about SAP integration and production impact.'),
  ('acc_northwind', 'pt-sofia', 'Sofia', 'Marchetti', 's.marchetti@lumenpharma.ie', null, 'purple', 'co-lumen', 'Asset Management', 'Asset Manager', 'Ireland', 'English', 'GMT', 'Pharmaceutical', '1001-5000', 14, 'senior', array['Asset register','Lifecycle & CAPEX planning','GxP compliance']::text[], array['Maintain asset data','Plan replacements','Audit trails']::text[], 'high', 'expert', 'expert', array['Meridian EAM']::text[], array['Assets','Reporting','Compliance']::text[], 'daily', 'desktop', 'expert', array['pe-asset']::text[], array['tag-analytical','tag-power-user']::text[], array['tag-data-quality','tag-reporting','tag-search']::text[], 'granted', true, false, 'English', '2026-06-15', 2, 'Mon/Wed', 'interviewed', null, 'No recording permission — notes only. Compliance/audit trail focus.'),
  ('acc_northwind', 'pt-david', 'David', 'Chen', 'd.chen@steelcore.se', null, 'rose', 'co-steelcore', 'IT', 'IT Systems Manager', 'Sweden', 'English', 'CET', 'Heavy Industry', '5000+', 16, 'lead', array['Integrations','SSO & security','System landscape']::text[], array['Manage integrations','Security reviews','Vendor coordination']::text[], 'high', 'expert', 'expert', array['Meridian EAM','Azure AD','SAP']::text[], array['Integrations','Admin']::text[], 'weekly', 'desktop', 'expert', array['pe-it']::text[], array['tag-analytical','tag-pragmatic']::text[], array['tag-integrations','tag-performance']::text[], 'pending', true, true, 'English', null, 0, 'By appointment', 'scheduled', '{"date":"2026-07-08","time":"10:00","projectId":"pr-planning"}'::jsonb, 'Consent form sent 2026-06-30; interview scheduled for planning study.'),
  ('acc_northwind', 'pt-marie', 'Marie', 'Dubois', 'm.dubois@brightfoods.be', null, 'amber', 'co-brightfoods', 'Warehouse', 'Spare Parts Coordinator', 'Belgium', 'French', 'CET', 'Food & Beverage', '5000+', 6, 'mid', array['Stock levels','Material issue','Goods receipt']::text[], array['Issue parts to WOs','Cycle counts','Reorder']::text[], 'medium', 'intermediate', 'intermediate', array['Meridian EAM']::text[], array['Stock','Purchasing','Work Orders']::text[], 'daily', 'both', 'intermediate', array['pe-warehouse']::text[], array['tag-pragmatic','tag-office-worker']::text[], array['tag-navigation','tag-search','tag-usability']::text[], 'granted', false, true, 'French', '2026-06-09', 1, 'Afternoons', 'interviewed', null, 'Prefers French; struggles with deep navigation to stock screens.'),
  ('acc_northwind', 'pt-hans', 'Hans', 'Müller', 'h.mueller@nordwind-energy.de', null, 'orange', 'co-nordwind', 'Procurement', 'Senior Purchaser', 'Germany', 'German', 'CET', 'Utilities & Energy', '1001-5000', 20, 'senior', array['Supplier management','Purchase orders','Critical parts']::text[], array['Convert requisitions','Track deliveries','Negotiate']::text[], 'medium', 'intermediate', 'intermediate', array['Meridian EAM']::text[], array['Purchasing','Stock']::text[], 'daily', 'desktop', 'intermediate', array['pe-purchaser']::text[], array['tag-office-worker','tag-change-resistant']::text[], array['tag-work-orders','tag-notifications','tag-integrations']::text[], 'granted', true, true, 'German', '2026-05-22', 1, 'Mornings', 'interviewed', null, null),
  ('acc_northwind', 'pt-nadia', 'Nadia', 'Petrova', 'n.petrova@riversidehealth.uk', null, 'pink', 'co-riverside', 'Estates', 'Facilities Technician', 'United Kingdom', 'English', 'GMT', 'Healthcare Facilities', '1001-5000', 4, 'junior', array['Reactive repairs','Rounds']::text[], array['Pick up jobs on tablet','Close work orders','Photo evidence']::text[], 'low', 'intermediate', 'expert', array['Meridian EAM','Meridian Go (mobile)']::text[], array['Mobile','Work Orders']::text[], 'daily', 'mobile', 'intermediate', array['pe-technician']::text[], array['tag-mobile-first','tag-early-adopter','tag-field-worker']::text[], array['tag-mobile-experience','tag-notifications','tag-performance']::text[], 'granted', false, true, 'English', '2026-06-27', 2, 'Flexible', 'interviewed', null, 'Young, mobile-native — a useful contrast to Piet.'),
  ('acc_northwind', 'pt-carlos', 'Carlos', 'Mendez', 'c.mendez@valtech.nl', null, 'blue', 'co-valtech', 'Maintenance', 'Maintenance Team Lead', 'Netherlands', 'Spanish', 'CET', 'Discrete Manufacturing', '201-1000', 11, 'lead', array['Shift coordination','Work assignment','Quality']::text[], array['Assign daily work','Review completions','Toolbox talks']::text[], 'medium', 'intermediate', 'intermediate', array['Meridian EAM','Meridian Go (mobile)']::text[], array['Work Orders','Planning','Mobile']::text[], 'daily', 'both', 'intermediate', array['pe-technician','pe-planner']::text[], array['tag-pragmatic','tag-field-worker']::text[], array['tag-planning','tag-work-orders','tag-notifications']::text[], 'granted', true, true, 'English', '2026-06-24', 1, 'Late afternoons', 'interviewed', null, null),
  ('acc_northwind', 'pt-anke', 'Anke', 'Visser', 'a.visser@alpinewater.ch', null, 'teal', 'co-alpine', 'Operations', 'Operations & Maintenance Lead', 'Switzerland', 'German', 'CET', 'Water Management', '51-200', 9, 'senior', array['Pump station upkeep','Small team management']::text[], array['Plan work','Field visits','Reporting to board']::text[], 'high', 'intermediate', 'intermediate', array['Meridian EAM']::text[], array['Work Orders','Assets','Reporting']::text[], 'daily', 'both', 'intermediate', array['pe-manager','pe-operations']::text[], array['tag-pragmatic','tag-data-driven']::text[], array['tag-reporting','tag-mobile-experience','tag-onboarding']::text[], 'granted', true, true, 'German', '2026-06-05', 1, 'Thursdays', 'interviewed', null, 'Small org — wears many hats; good for SMB perspective.'),
  ('acc_northwind', 'pt-yusuf', 'Yusuf', 'Demir', 'y.demir@portside.nl', null, 'violet', 'co-portside', 'Planning', 'Maintenance Planner', 'Netherlands', 'Turkish', 'CET', 'Logistics & Ports', '201-1000', 7, 'mid', array['Preventive scheduling','Contractor coordination']::text[], array['Plan PM','Coordinate contractors','Update backlog']::text[], 'medium', 'expert', 'expert', array['Meridian EAM']::text[], array['Planning','Work Orders','Purchasing']::text[], 'daily', 'desktop', 'expert', array['pe-planner']::text[], array['tag-analytical','tag-power-user','tag-ai-enthusiast']::text[], array['tag-planning','tag-integrations','tag-ai']::text[], 'granted', true, true, 'English', '2026-06-30', 1, 'Flexible', 'interviewed', null, null),
  ('acc_northwind', 'pt-emma', 'Emma', 'Nováková', 'e.novakova@lumenpharma.ie', null, 'green', 'co-lumen', 'Quality', 'System Administrator', 'Ireland', 'English', 'GMT', 'Pharmaceutical', '1001-5000', 5, 'mid', array['User management','Master data','Configuration']::text[], array['Manage users','Maintain lists','Support colleagues']::text[], 'medium', 'expert', 'expert', array['Meridian EAM']::text[], array['Admin','Reporting']::text[], 'daily', 'desktop', 'expert', array['pe-admin']::text[], array['tag-power-user','tag-early-adopter']::text[], array['tag-usability','tag-onboarding','tag-data-quality']::text[], 'expired', true, true, 'English', '2025-11-14', 1, 'Mornings', 'available', null, 'Consent expired — needs re-consent before next contact.'),
  ('acc_northwind', 'pt-robert', 'Robert', 'Andersson', 'r.andersson@steelcore.se', null, 'slate', 'co-steelcore', 'Executive', 'VP Operations', 'Sweden', 'Swedish', 'CET', 'Heavy Industry', '5000+', 25, 'executive', array['Strategy','Investment decisions','Risk']::text[], array['Review dashboards','Steer investments']::text[], 'high', 'beginner', 'intermediate', array['Meridian EAM']::text[], array['Dashboards']::text[], 'monthly', 'both', 'beginner', array['pe-executive']::text[], array['tag-data-driven','tag-office-worker']::text[], array['tag-dashboards','tag-reporting']::text[], 'granted', true, false, 'English', null, 0, 'Very limited — 30 min slots', 'contacted', null, 'Executive sponsor perspective; hard to schedule.'),
  ('acc_northwind', 'pt-priya', 'Priya', 'Nair', 'p.nair@riversidehealth.uk', null, 'cyan', 'co-riverside', 'Reliability', 'Reliability & Compliance Engineer', 'United Kingdom', 'English', 'GMT', 'Healthcare Facilities', '1001-5000', 8, 'senior', array['Statutory compliance','Asset criticality','PM optimization']::text[], array['Track compliance','Analyze failures','Adjust PM']::text[], 'high', 'expert', 'expert', array['Meridian EAM','Power BI']::text[], array['Assets','Reporting','Compliance']::text[], 'daily', 'desktop', 'expert', array['pe-reliability']::text[], array['tag-analytical','tag-data-driven','tag-ai-enthusiast']::text[], array['tag-reporting','tag-ai','tag-data-quality']::text[], 'granted', true, true, 'English', '2026-06-19', 1, 'Tuesdays', 'interviewed', null, null),
  ('acc_northwind', 'pt-thomas', 'Thomas', 'Berg', 't.berg@alpinewater.ch', null, 'amber', 'co-alpine', 'Field Service', 'Field Service Technician', 'Switzerland', 'German', 'CET', 'Water Management', '51-200', 3, 'junior', array['Pump maintenance','Remote station visits']::text[], array['Drive to stations','Inspect pumps','Log offline then sync']::text[], 'low', 'intermediate', 'intermediate', array['Meridian Go (mobile)']::text[], array['Mobile','Work Orders']::text[], 'daily', 'field-mobile', 'beginner', array['pe-technician']::text[], array['tag-field-worker','tag-mobile-first']::text[], array['tag-mobile-experience','tag-performance','tag-search']::text[], 'granted', false, true, 'German', '2026-06-13', 1, 'End of day', 'interviewed', null, 'Frequently offline at remote pump stations — sync pain point.')
on conflict (id) do nothing;

insert into public.projects (account_id, id, name, description, objective, product_area, status, start_date, end_date, owner_id, member_ids, participant_ids, research_questions, success_criteria, methodology) values
  ('acc_northwind', 'pr-mobile', 'Mobile Work Order Experience', 'Understand how field technicians use Meridian Go to receive, execute, and close work orders — especially with poor connectivity.', 'Identify the top friction points in the mobile work order flow and validate concepts for an offline-first redesign.', 'Mobile', 'analysis', '2026-05-04', '2026-07-10', 'u-sanne', array['u-sanne','u-tom','u-julia','u-marco']::text[], array['pt-lukas','pt-piet','pt-nadia','pt-thomas','pt-carlos']::text[], '[{"id":"rq-m1","text":"Where do technicians lose the most time in the mobile flow?","answered":true},{"id":"rq-m2","text":"How do they cope when connectivity drops mid-job?","answered":true},{"id":"rq-m3","text":"What information do they need before starting a job?","answered":false},{"id":"rq-m4","text":"Would an offline-first model change trust in the app?","answered":false}]'::jsonb, array['5+ technicians across 3 industries interviewed','Prioritized list of top 5 mobile friction points','Validated offline concept with ≥4 participants']::text[], 'Contextual inquiry + moderated concept testing'),
  ('acc_northwind', 'pr-planning', 'Planning & Scheduling Deep Dive', 'Explore how planners build and adjust schedules, and where the current scheduling board falls short.', 'Map the end-to-end planning workflow and uncover opportunities to reduce manual rescheduling effort.', 'Planning', 'in-progress', '2026-06-01', '2026-08-15', 'u-tom', array['u-tom','u-lena','u-julia']::text[], array['pt-fatima','pt-yusuf','pt-carlos','pt-david']::text[], '[{"id":"rq-p1","text":"What triggers a re-plan and how disruptive is it?","answered":true},{"id":"rq-p2","text":"How do planners balance PM vs. corrective work?","answered":false},{"id":"rq-p3","text":"Where could AI suggest schedule optimizations?","answered":false}]'::jsonb, array['Journey map of the weekly planning cycle','Identify 3 automation opportunities']::text[], 'Semi-structured interviews + task observation'),
  ('acc_northwind', 'pr-reporting', 'Reporting & Dashboards Needs', 'Understand what managers, reliability engineers, and executives need from reporting and dashboards.', 'Define the reporting jobs-to-be-done across personas and prioritize dashboard improvements.', 'Reporting', 'in-progress', '2026-05-20', '2026-07-31', 'u-sanne', array['u-sanne','u-lena']::text[], array['pt-james','pt-ingrid','pt-amara','pt-priya','pt-anke','pt-robert']::text[], '[{"id":"rq-r1","text":"Which KPIs matter most per persona?","answered":true},{"id":"rq-r2","text":"How much do people export to Power BI and why?","answered":true},{"id":"rq-r3","text":"What would make dashboards trustworthy enough to act on?","answered":false}]'::jsonb, array['Persona-specific KPI matrix','Recommendations for default dashboards']::text[], 'Interviews + artifact review'),
  ('acc_northwind', 'pr-onboarding', 'New User Onboarding', 'Study how first-time users learn Meridian and where they get stuck in the first two weeks.', 'Reduce time-to-productivity for new technicians and administrators.', 'Platform', 'recruiting', '2026-06-25', '2026-09-01', 'u-tom', array['u-tom','u-julia']::text[], array['pt-piet','pt-marie','pt-emma','pt-thomas']::text[], '[{"id":"rq-o1","text":"What are the first tasks new users attempt?","answered":false},{"id":"rq-o2","text":"Where does the current onboarding break down?","answered":false}]'::jsonb, array['Onboarding friction inventory','Concept for guided first-run']::text[], 'Diary study + first-use sessions'),
  ('acc_northwind', 'pr-ai', 'AI Assistance Opportunities', 'Discover where AI could meaningfully reduce manual effort across maintenance roles.', 'Prioritize AI use-cases by desirability and feasibility, grounded in real workflows.', 'AI', 'planning', '2026-07-01', '2026-09-30', 'u-sanne', array['u-sanne','u-tom','u-marco']::text[], array['pt-ingrid','pt-priya','pt-yusuf']::text[], '[{"id":"rq-a1","text":"Which manual tasks feel most automatable to users?","answered":false},{"id":"rq-a2","text":"How much AI autonomy are users comfortable with?","answered":false}]'::jsonb, array['Ranked AI opportunity backlog']::text[], 'Concept workshops'),
  ('acc_northwind', 'pr-search', 'Search & Findability Study', 'Completed study on how users locate assets, work orders, and parts across the product.', 'Establish a findability baseline and quick wins for global search.', 'Platform', 'completed', '2026-02-10', '2026-04-30', 'u-sanne', array['u-sanne','u-tom','u-julia']::text[], array['pt-fatima','pt-marie','pt-sofia','pt-lukas']::text[], '[{"id":"rq-s1","text":"How do users currently find records?","answered":true},{"id":"rq-s2","text":"What are the biggest search frustrations?","answered":true}]'::jsonb, array['Findability baseline','Top 5 search quick wins delivered']::text[], 'Tree testing + interviews')
on conflict (id) do nothing;

insert into public.interviews (account_id, id, title, date, researcher_id, participant_id, project_ids, duration_minutes, meeting_link, has_recording, sentiment, ai_summary, key_observations, insight_ids, attachments, follow_ups, transcript_id) values
  ('acc_northwind', 'iv-lukas-1', 'Field ride-along — turbine work orders', '2026-06-18', 'u-sanne', 'pt-lukas', array['pr-mobile']::text[], 58, 'https://meet.example.com/lukas-fieldwork', true, 'negative', 'Lukas walks through a full turbine work order on Meridian Go. The dominant theme is connectivity: sessions time out during climbs, and he has no confidence that updates sync. He works around this by screenshotting and photographing nameplates instead of searching for assets. Asset search is perceived as slower than the physical repair.', array['Session timeout during climb loses in-progress work order','Screenshots used as a personal ''save'' mechanism due to sync distrust','Photographs nameplate rather than searching asset register']::text[], array['in-offline-sync','in-mobile-offline-trust','in-search-global']::text[], '[{"id":"at-lukas-rec","name":"lukas-ridealong.mp4","kind":"video","sizeLabel":"612 MB","addedDate":"2026-06-18"},{"id":"at-lukas-tr","name":"lukas-transcript.txt","kind":"transcript","sizeLabel":"42 KB","addedDate":"2026-06-18"},{"id":"at-lukas-photo","name":"nameplate-photos.zip","kind":"image","sizeLabel":"18 MB","addedDate":"2026-06-18"}]'::jsonb, '[{"id":"fu-lukas-1","text":"Test offline-first prototype with Lukas","done":false,"assigneeId":"u-julia"},{"id":"fu-lukas-2","text":"Quantify timeout frequency from telemetry","done":false,"assigneeId":"u-tom"}]'::jsonb, 'tr-lukas'),
  ('acc_northwind', 'iv-piet-1', 'Crane technician — resistance to mobile', '2026-05-30', 'u-tom', 'pt-piet', array['pr-mobile','pr-onboarding']::text[], 45, null, true, 'negative', 'Piet, a 22-year veteran, contrasts the reliability of paper with the friction of the mobile app. His resistance is rooted in trust and a steep, unguided learning curve rather than unwillingness. A strong counter-perspective to younger, mobile-native technicians.', array['Trust in paper stems from its reliability, not nostalgia','No guided onboarding for first mobile use','Would adopt if the tool proved dependable']::text[], array['in-mobile-nav-depth','in-onboard-firstrun']::text[], '[{"id":"at-piet-rec","name":"piet-interview.m4a","kind":"audio","sizeLabel":"38 MB","addedDate":"2026-05-30"}]'::jsonb, '[{"id":"fu-piet-1","text":"Recruit 2 more veteran technicians","done":true,"assigneeId":"u-tom"}]'::jsonb, null),
  ('acc_northwind', 'iv-nadia-1', 'Ward rounds — mobile performance', '2026-06-27', 'u-sanne', 'pt-nadia', array['pr-mobile']::text[], 40, null, true, 'mixed', 'Nadia is mobile-native and generally positive, but hits performance walls on hospital wards where pages hang and photo uploads fail repeatedly. Notifications are frequent but she engages with them, unlike some peers.', array['Page load stalls in low-signal ward areas','Photo upload frequently fails and must be retried']::text[], array['in-mobile-photo','in-notif-noise']::text[], '[{"id":"at-nadia-rec","name":"nadia-session.mp4","kind":"video","sizeLabel":"480 MB","addedDate":"2026-06-27"}]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-thomas-1', 'Remote pump stations — offline reality', '2026-06-13', 'u-tom', 'pt-thomas', array['pr-mobile']::text[], 35, null, true, 'negative', 'Thomas services remote pump stations with no cellular signal. His entire workflow is offline-then-sync via paper as an intermediary, which duplicates effort and risks transcription errors.', array['No connectivity at stations','Paper used as offline bridge, later re-keyed']::text[], array['in-offline-sync','in-mobile-offline-trust']::text[], '[{"id":"at-thomas-rec","name":"thomas-call.m4a","kind":"audio","sizeLabel":"28 MB","addedDate":"2026-06-13"}]'::jsonb, '[{"id":"fu-thomas-1","text":"Map offline data-loss risk points","done":false}]'::jsonb, null),
  ('acc_northwind', 'iv-carlos-1', 'Team lead — notification overload', '2026-06-24', 'u-tom', 'pt-carlos', array['pr-mobile','pr-planning']::text[], 42, null, true, 'negative', 'Carlos manages a shift team and describes notification fatigue: alerts are undifferentiated, so his crew dismisses everything, occasionally missing urgent work.', array['Notifications lack priority differentiation','Alert fatigue causes missed urgent jobs']::text[], array['in-notif-noise']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-fatima-1', 'Planner workflow — the rescheduling problem', '2026-06-25', 'u-tom', 'pt-fatima', array['pr-planning']::text[], 62, 'https://meet.example.com/fatima-planning', true, 'mixed', 'Fatima demonstrates the weekly planning cycle. A single breakdown cascades into hours of manual drag-and-drop rescheduling. She is enthusiastic about AI that proposes a re-plan for her to approve, and frustrated that saved filters aren''t remembered between sessions.', array['One breakdown triggers hours of manual re-planning','Strong appetite for approve-a-suggestion AI model','Filters reset every session, forcing rework']::text[], array['in-plan-replan-cost','in-plan-ai-opt','in-search-recent']::text[], '[{"id":"at-fatima-rec","name":"fatima-planning.mp4","kind":"video","sizeLabel":"702 MB","addedDate":"2026-06-25"},{"id":"at-fatima-tr","name":"fatima-transcript.txt","kind":"transcript","sizeLabel":"51 KB","addedDate":"2026-06-25"}]'::jsonb, '[{"id":"fu-fatima-1","text":"Sketch approve-a-replan concept","done":false,"assigneeId":"u-julia"},{"id":"fu-fatima-2","text":"Validate saved-filters quick win with dev","done":false,"assigneeId":"u-lena"}]'::jsonb, 'tr-fatima'),
  ('acc_northwind', 'iv-yusuf-1', 'Planner — attitudes to AI autonomy', '2026-06-30', 'u-tom', 'pt-yusuf', array['pr-planning','pr-ai']::text[], 48, null, true, 'neutral', 'Yusuf is open to AI assistance but firmly wants a human-in-the-loop model. He''d accept suggestions and optimizations but not autonomous scheduling. Also notes limited visibility of live technician status.', array['Wants AI to suggest, not decide','Lacks real-time technician status visibility']::text[], array['in-plan-ai-opt','in-plan-visibility']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-james-1', 'Maintenance manager — dashboard trust', '2026-06-11', 'u-sanne', 'pt-james', array['pr-reporting']::text[], 50, null, true, 'negative', 'James won''t act on dashboards because he can''t tell how fresh the data is. KPI needs are SLA-focused and differ from those of engineers. Data-freshness signaling is the key trust lever.', array['Data-freshness ambiguity blocks action','SLA-centric KPI needs']::text[], array['in-report-trust','in-report-kpi-persona']::text[], '[{"id":"at-james-rec","name":"james-interview.mp4","kind":"video","sizeLabel":"520 MB","addedDate":"2026-06-11"}]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-ingrid-1', 'Reliability engineer — the Power BI escape hatch', '2026-06-28', 'u-sanne', 'pt-ingrid', array['pr-reporting','pr-ai']::text[], 55, null, true, 'mixed', 'Ingrid bypasses built-in reporting entirely for Power BI because native reports can''t express her analytical questions. She''s an AI enthusiast who wants automated failure-pattern clustering across large asset fleets.', array['Native reports too rigid for analytical work','Wants AI failure clustering']::text[], array['in-report-export-bi','in-ai-failure-pattern']::text[], '[{"id":"at-ingrid-rec","name":"ingrid-call.mp4","kind":"video","sizeLabel":"610 MB","addedDate":"2026-06-28"}]'::jsonb, '[{"id":"fu-ingrid-1","text":"Collect example Power BI reports she rebuilt","done":false}]'::jsonb, null),
  ('acc_northwind', 'iv-amara-1', 'Operations manager — SAP integration trust', '2026-06-20', 'u-sanne', 'pt-amara', array['pr-reporting']::text[], 47, null, true, 'negative', 'Amara describes how discrepancies between SAP and Meridian stock figures erode trust in both systems, leading planners to double-check manually and slowing decisions.', array['SAP/Meridian stock mismatches erode trust','Manual double-checking as a workaround']::text[], array['in-integration-sap','in-report-trust']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-priya-1', 'Reliability & compliance — AI for failure patterns', '2026-06-19', 'u-sanne', 'pt-priya', array['pr-reporting','pr-ai']::text[], 52, null, true, 'positive', 'Priya manages statutory compliance across a large asset base and sees clear value in AI clustering of failure patterns, which is infeasible manually at her scale. KPI needs are compliance- and criticality-driven.', array['Manual failure analysis doesn''t scale','Compliance/criticality KPI focus']::text[], array['in-ai-failure-pattern','in-report-kpi-persona']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-anke-1', 'SMB ops lead — reporting simplicity', '2026-06-05', 'u-sanne', 'pt-anke', array['pr-reporting','pr-onboarding']::text[], 38, null, true, 'mixed', 'Anke represents a small team with no analyst. She needs fast, simple, pre-built reports and finds the current reporting setup too heavy for her context.', array['No dedicated analyst — needs pre-built reports','Current reporting too heavy for SMB']::text[], array['in-report-export-bi','in-onboard-firstrun']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-marie-1', 'Warehouse — stock findability', '2026-06-09', 'u-tom', 'pt-marie', array['pr-search','pr-onboarding']::text[], 36, null, true, 'negative', 'Marie reaches stock screens via a four-level menu every time and finds search unreliable because it doesn''t match colloquial part names. Deep navigation is her single biggest daily cost.', array['Four-level navigation to stock','Search misses colloquial part names']::text[], array['in-stock-findability','in-search-global']::text[], '[]'::jsonb, '[]'::jsonb, null),
  ('acc_northwind', 'iv-sofia-1', 'Asset manager — search reliability', '2026-06-15', 'u-sanne', 'pt-sofia', array['pr-search']::text[], 44, null, false, 'negative', 'Sofia (no recording — notes only) maintains a private spreadsheet of asset numbers because she can''t trust in-product search to find them, a clear findability and data-trust failure.', array['Private spreadsheet workaround','Low trust in asset search']::text[], array['in-search-global','in-integration-sap']::text[], '[{"id":"at-sofia-notes","name":"sofia-notes.pdf","kind":"document","sizeLabel":"220 KB","addedDate":"2026-06-15"}]'::jsonb, '[]'::jsonb, null)
on conflict (id) do nothing;

insert into public.insights (account_id, id, title, description, evidence, type, confidence, severity, impact, created_date, created_by, participant_ids, interview_ids, project_ids, theme_ids, tag_ids, product_area, persona_ids) values
  ('acc_northwind', 'in-offline-sync', 'Connectivity loss silently drops in-progress work orders', 'Technicians lose work orders when sessions time out during climbs or in low-signal areas. There is no reliable offline capture, so data and time are lost.', 'Observed directly on Lukas''s ride-along and corroborated by Thomas at remote pump stations. Both work around it with paper or screenshots.', 'pain-point', 'high', 'critical', 'high', '2026-06-19', 'u-sanne', array['pt-lukas','pt-thomas']::text[], array['iv-lukas-1','iv-thomas-1']::text[], array['pr-mobile']::text[], array['th-mobile-field','th-trust-data']::text[], array['tag-mobile-experience','tag-performance']::text[], 'Mobile', array['pe-technician']::text[]),
  ('acc_northwind', 'in-mobile-offline-trust', 'Sync uncertainty erodes trust in the mobile app', 'Even when data does save, users can''t tell whether it synced. The uncertainty — not the wait — drives distrust and defensive workarounds like screenshotting.', 'Lukas screenshots every entry ''just in case''; Thomas re-keys from paper to be safe.', 'insight', 'high', 'high', 'high', '2026-06-20', 'u-sanne', array['pt-lukas','pt-thomas']::text[], array['iv-lukas-1','iv-thomas-1']::text[], array['pr-mobile']::text[], array['th-mobile-field','th-trust-data']::text[], array['tag-mobile-experience']::text[], 'Mobile', array['pe-technician']::text[]),
  ('acc_northwind', 'in-search-global', 'No reliable way to find assets, parts, or records', 'Search requires exact codes and misses colloquial names, so users avoid it entirely — photographing nameplates, keeping private spreadsheets, or navigating by memory.', 'Recurs across three roles and two studies: Lukas (assets), Marie (parts), Sofia (asset numbers).', 'pain-point', 'high', 'high', 'high', '2026-04-22', 'u-sanne', array['pt-lukas','pt-marie','pt-sofia']::text[], array['iv-lukas-1','iv-marie-1','iv-sofia-1']::text[], array['pr-mobile','pr-search']::text[], array['th-findability']::text[], array['tag-search','tag-navigation']::text[], 'Platform', array['pe-technician','pe-warehouse','pe-asset']::text[]),
  ('acc_northwind', 'in-mobile-nav-depth', 'Too many taps to start and complete a job', 'The mobile flow requires excessive navigation to begin work, which compounds the friction for less digitally-confident technicians.', 'Piet contrasts the immediacy of paper with the app''s steps.', 'observation', 'medium', 'medium', 'medium', '2026-06-01', 'u-tom', array['pt-piet']::text[], array['iv-piet-1']::text[], array['pr-mobile','pr-onboarding']::text[], array['th-mobile-field','th-onboarding-learn']::text[], array['tag-navigation','tag-usability']::text[], 'Mobile', array['pe-technician']::text[]),
  ('acc_northwind', 'in-onboard-firstrun', 'No guided first-run leaves new users to flounder', 'New and less-technical users lack any guided onboarding, so adoption depends on individual persistence. Resistance is often about trust and learnability, not unwillingness.', 'Piet (veteran) and Anke (SMB, no analyst) both describe an unsupported start.', 'opportunity', 'medium', 'medium', 'high', '2026-06-06', 'u-tom', array['pt-piet','pt-anke']::text[], array['iv-piet-1','iv-anke-1']::text[], array['pr-onboarding']::text[], array['th-onboarding-learn']::text[], array['tag-onboarding','tag-usability']::text[], 'Platform', array['pe-technician','pe-manager']::text[]),
  ('acc_northwind', 'in-mobile-photo', 'Photo attachment fails repeatedly on weak signal', 'Attaching evidence photos often takes multiple attempts, adding friction to a core mobile task.', 'Nadia reports up to four retries per upload on the ward.', 'pain-point', 'high', 'medium', 'medium', '2026-06-27', 'u-sanne', array['pt-nadia']::text[], array['iv-nadia-1']::text[], array['pr-mobile']::text[], array['th-mobile-field']::text[], array['tag-mobile-experience','tag-performance']::text[], 'Mobile', array['pe-technician']::text[]),
  ('acc_northwind', 'in-notif-noise', 'Undifferentiated notifications cause alert fatigue', 'Because notifications lack priority, teams dismiss them wholesale and occasionally miss urgent work.', 'Carlos''s crew swipes alerts away; Nadia engages but finds them frequent.', 'pain-point', 'high', 'high', 'medium', '2026-06-24', 'u-tom', array['pt-carlos','pt-nadia']::text[], array['iv-carlos-1','iv-nadia-1']::text[], array['pr-mobile','pr-planning']::text[], array['th-mobile-field']::text[], array['tag-notifications']::text[], 'Mobile', array['pe-technician']::text[]),
  ('acc_northwind', 'in-plan-replan-cost', 'A single breakdown cascades into hours of manual rescheduling', 'Unplanned events force planners to manually drag dozens of jobs and re-check technician capacity, consuming much of the morning.', 'Fatima demonstrated ~30 jobs moved by hand after one breakdown.', 'pain-point', 'high', 'high', 'high', '2026-06-26', 'u-tom', array['pt-fatima']::text[], array['iv-fatima-1']::text[], array['pr-planning']::text[], array['th-planning-scheduling']::text[], array['tag-planning','tag-work-orders']::text[], 'Planning', array['pe-planner']::text[]),
  ('acc_northwind', 'in-plan-ai-opt', 'Planners want AI to propose a re-plan they can approve', 'A human-in-the-loop model — AI suggests a revised schedule, planner approves/adjusts — is highly desirable and estimated to save ~1 hour/day.', 'Fatima and Yusuf independently describe ''suggest, don''t decide''.', 'opportunity', 'medium', 'medium', 'high', '2026-06-30', 'u-tom', array['pt-fatima','pt-yusuf']::text[], array['iv-fatima-1','iv-yusuf-1']::text[], array['pr-planning','pr-ai']::text[], array['th-ai-assist','th-planning-scheduling']::text[], array['tag-ai','tag-planning']::text[], 'Planning', array['pe-planner']::text[]),
  ('acc_northwind', 'in-search-recent', 'Saved/remembered filters would be a high-value quick win', 'Planners rebuild identical filters every session. Persisting the last view (or saved filters) reclaims minutes daily with low engineering cost.', 'Fatima rebuilds the same filter every morning.', 'feature-request', 'high', 'low', 'medium', '2026-06-26', 'u-tom', array['pt-fatima']::text[], array['iv-fatima-1']::text[], array['pr-planning']::text[], array['th-findability','th-planning-scheduling']::text[], array['tag-search','tag-planning','tag-quick-win']::text[], 'Platform', array['pe-planner']::text[]),
  ('acc_northwind', 'in-plan-visibility', 'Planners lack real-time visibility of technician status', 'Without live status, planners guess at availability when re-planning, reducing schedule quality.', 'Raised by Yusuf; needs further validation.', 'user-need', 'low', 'medium', 'medium', '2026-06-30', 'u-tom', array['pt-yusuf']::text[], array['iv-yusuf-1']::text[], array['pr-planning']::text[], array['th-planning-scheduling']::text[], array['tag-planning','tag-needs-validation']::text[], 'Planning', array['pe-planner']::text[]),
  ('acc_northwind', 'in-report-trust', 'Ambiguous data freshness stops people acting on dashboards', 'Managers won''t make decisions from dashboards because they can''t tell how current the figures are. Clear freshness signaling is the key trust lever.', 'James won''t act without knowing the data''s age; Amara cites cross-system mismatch.', 'pain-point', 'high', 'high', 'high', '2026-06-12', 'u-sanne', array['pt-james','pt-amara']::text[], array['iv-james-1','iv-amara-1']::text[], array['pr-reporting']::text[], array['th-reporting-insight','th-trust-data']::text[], array['tag-dashboards','tag-reporting']::text[], 'Reporting', array['pe-manager','pe-operations']::text[]),
  ('acc_northwind', 'in-report-kpi-persona', 'KPI needs diverge sharply by persona', 'Managers want SLA/compliance KPIs; reliability engineers want failure and criticality analytics. A single default dashboard cannot serve both.', 'Contrast between James (SLA) and Priya (criticality/failure).', 'insight', 'medium', 'medium', 'medium', '2026-06-20', 'u-sanne', array['pt-james','pt-priya']::text[], array['iv-james-1','iv-priya-1']::text[], array['pr-reporting']::text[], array['th-reporting-insight']::text[], array['tag-dashboards','tag-reporting']::text[], 'Reporting', array['pe-manager','pe-reliability']::text[]),
  ('acc_northwind', 'in-report-export-bi', 'Users escape to Power BI because native reports are too rigid', 'Analytical users export data to Power BI because built-in reporting can''t express their questions. SMB users, lacking analysts, are simply stuck.', 'Ingrid exports everything; Anke needs pre-built simplicity she can''t get.', 'pain-point', 'high', 'high', 'high', '2026-06-28', 'u-sanne', array['pt-ingrid','pt-anke']::text[], array['iv-ingrid-1','iv-anke-1']::text[], array['pr-reporting']::text[], array['th-reporting-insight']::text[], array['tag-reporting','tag-integrations']::text[], 'Reporting', array['pe-reliability','pe-manager']::text[]),
  ('acc_northwind', 'in-ai-failure-pattern', 'Reliability engineers want AI to cluster failure patterns', 'At fleet scale, manually spotting failure patterns is infeasible. AI-driven clustering is a clearly desirable, high-impact use-case.', 'Priya (400+ pumps) and Ingrid both request it explicitly.', 'opportunity', 'medium', 'medium', 'high', '2026-06-28', 'u-sanne', array['pt-priya','pt-ingrid']::text[], array['iv-priya-1','iv-ingrid-1']::text[], array['pr-reporting','pr-ai']::text[], array['th-ai-assist','th-reporting-insight']::text[], array['tag-ai','tag-reporting']::text[], 'AI', array['pe-reliability']::text[]),
  ('acc_northwind', 'in-integration-sap', 'SAP/Meridian stock mismatches erode trust in both systems', 'When integrated systems disagree on stock, users stop trusting all of them and revert to manual verification, slowing operations.', 'Amara''s planners double-check; Sofia keeps a private register.', 'pain-point', 'medium', 'high', 'high', '2026-06-20', 'u-sanne', array['pt-amara','pt-sofia']::text[], array['iv-amara-1','iv-sofia-1']::text[], array['pr-reporting','pr-search']::text[], array['th-integration','th-trust-data']::text[], array['tag-integrations','tag-data-quality']::text[], 'Integrations', array['pe-operations','pe-asset']::text[]),
  ('acc_northwind', 'in-stock-findability', 'Deep menu navigation slows every warehouse task', 'Reaching the stock screen takes four menu levels each time, a constant tax on high-frequency warehouse work.', 'Marie navigates four menus on every visit.', 'pain-point', 'high', 'medium', 'medium', '2026-06-09', 'u-tom', array['pt-marie']::text[], array['iv-marie-1']::text[], array['pr-search','pr-onboarding']::text[], array['th-findability']::text[], array['tag-navigation','tag-usability']::text[], 'Platform', array['pe-warehouse']::text[])
on conflict (id) do nothing;

insert into public.transcripts (account_id, id, interview_id, language, segments, comments) values
  ('acc_northwind', 'tr-lukas', 'iv-lukas-1', 'English (translated from German)', '[{"id":"s-l1","speaker":"Sanne","speakerRole":"researcher","startSeconds":12,"text":"Thanks for letting me ride along today, Lukas. Can you walk me through what happens when a work order comes in?"},{"id":"s-l2","speaker":"Lukas","speakerRole":"participant","startSeconds":28,"text":"Sure. I get a notification on the phone, open Meridian Go, and there''s the work order. The problem starts when I have to climb the turbine. It takes ten, fifteen minutes to get up top."},{"id":"s-l3","speaker":"Sanne","speakerRole":"researcher","startSeconds":62,"text":"And what happens to the app during that climb?"},{"id":"s-l4","speaker":"Lukas","speakerRole":"participant","startSeconds":70,"text":"By the time I''ve climbed up, the app has logged me out and I''ve lost the work order I opened. So I have to log in again, find it again, up there in the wind. It''s frustrating."},{"id":"s-l5","speaker":"Sanne","speakerRole":"researcher","startSeconds":130,"text":"How do you deal with finding the right asset once you''re up there?"},{"id":"s-l6","speaker":"Lukas","speakerRole":"participant","startSeconds":140,"text":"Honestly? I take a photo of the nameplate because searching for the asset takes longer than the repair itself. The search wants an exact code and I don''t have it memorized for every gearbox."},{"id":"s-l7","speaker":"Sanne","speakerRole":"researcher","startSeconds":210,"text":"Let''s talk about saving your work. When you enter findings, how confident are you that it''s recorded?"},{"id":"s-l8","speaker":"Lukas","speakerRole":"participant","startSeconds":224,"text":"Not confident at all. I never really know if my update actually saved when the signal is weak. So I screenshot everything before I hit save, just in case it disappears."},{"id":"s-l9","speaker":"Sanne","speakerRole":"researcher","startSeconds":300,"text":"If the app worked completely offline and synced later, would that change things for you?"},{"id":"s-l10","speaker":"Lukas","speakerRole":"participant","startSeconds":312,"text":"That would be huge. As long as I can see clearly that it will sync, and it doesn''t just vanish. The uncertainty is the worst part, more than the waiting."}]'::jsonb, '[{"id":"cm-l1","segmentId":"s-l4","authorId":"u-julia","text":"This is the moment to prototype — persistent session + resume-where-you-were.","date":"2026-06-19"},{"id":"cm-l2","segmentId":"s-l8","authorId":"u-marco","text":"The screenshot workaround shows up in 3 other interviews too. Strong signal.","date":"2026-06-20"}]'::jsonb),
  ('acc_northwind', 'tr-fatima', 'iv-fatima-1', 'English (translated from Dutch)', '[{"id":"s-f1","speaker":"Tom","speakerRole":"researcher","startSeconds":20,"text":"Walk me through a normal Monday morning on the scheduling board."},{"id":"s-f2","speaker":"Fatima","speakerRole":"participant","startSeconds":34,"text":"I open the board and it''s already full from the weekend. I filter to my area, my week, my technicians — and I do that every single morning from scratch."},{"id":"s-f3","speaker":"Tom","speakerRole":"researcher","startSeconds":90,"text":"Every morning from scratch? The filters don''t persist?"},{"id":"s-f4","speaker":"Fatima","speakerRole":"participant","startSeconds":98,"text":"No. I rebuild the same filter every morning because it never remembers what I was looking at. Small thing, but it''s five minutes of clicking before I even start."},{"id":"s-f5","speaker":"Tom","speakerRole":"researcher","startSeconds":160,"text":"Now, what happens when something unplanned comes in — a breakdown?"},{"id":"s-f6","speaker":"Fatima","speakerRole":"participant","startSeconds":172,"text":"That''s the real pain. One machine breakdown and I''m dragging thirty jobs around the board by hand for the rest of the morning. Everything downstream shifts, and I have to check each technician''s capacity manually."},{"id":"s-f7","speaker":"Tom","speakerRole":"researcher","startSeconds":250,"text":"If you could wave a wand, what would help most in that moment?"},{"id":"s-f8","speaker":"Fatima","speakerRole":"participant","startSeconds":262,"text":"If the system could propose a new plan and I just approve it, that''s an hour back every single day. I don''t need it to be perfect — I need a starting point I can adjust."},{"id":"s-f9","speaker":"Tom","speakerRole":"researcher","startSeconds":330,"text":"So you''d want to stay in control of the final decision."},{"id":"s-f10","speaker":"Fatima","speakerRole":"participant","startSeconds":338,"text":"Absolutely. Suggest, don''t decide. But suggesting would already save me most of the manual dragging."}]'::jsonb, '[{"id":"cm-f1","segmentId":"s-f8","authorId":"u-lena","text":"This is the north-star for the AI planning concept. Let''s storyboard it.","date":"2026-06-26"}]'::jsonb)
on conflict (id) do nothing;

insert into public.transcript_highlights (account_id, id, transcript_id, segment_id, start_pos, end_pos, text, kind, note, tag_ids, created_by, linked_insight_id) values
  ('acc_northwind', 'hl-l1', 'tr-lukas', 's-l4', 0, 62, 'By the time I''ve climbed up, the app has logged me out and I''ve lost the work order I opened.', 'pain-point', 'Session timeout during climb', array['tag-mobile-experience','tag-performance']::text[], 'u-sanne', 'in-offline-sync'),
  ('acc_northwind', 'hl-l2', 'tr-lukas', 's-l6', 0, 80, 'I take a photo of the nameplate because searching for the asset takes longer than the repair itself', 'pain-point', 'Asset search slower than repair', array['tag-search']::text[], 'u-sanne', 'in-search-global'),
  ('acc_northwind', 'hl-l3', 'tr-lukas', 's-l8', 0, 70, 'I never really know if my update actually saved when the signal is weak', 'insight', 'Sync distrust → screenshot workaround', array['tag-mobile-experience']::text[], 'u-sanne', 'in-mobile-offline-trust'),
  ('acc_northwind', 'hl-l4', 'tr-lukas', 's-l10', 0, 40, 'That would be huge. As long as I can see clearly that it will sync', 'opportunity', 'Offline-first with visible sync state', array['tag-mobile-experience']::text[], 'u-sanne', null),
  ('acc_northwind', 'hl-f1', 'tr-fatima', 's-f4', 0, 70, 'I rebuild the same filter every morning because it never remembers what I was looking at', 'pain-point', 'Filters don''t persist', array['tag-planning','tag-usability']::text[], 'u-tom', 'in-search-recent'),
  ('acc_northwind', 'hl-f2', 'tr-fatima', 's-f6', 0, 90, 'One machine breakdown and I''m dragging thirty jobs around the board by hand for the rest of the morning', 'pain-point', 'Rescheduling cascade', array['tag-planning','tag-work-orders']::text[], 'u-tom', 'in-plan-replan-cost'),
  ('acc_northwind', 'hl-f3', 'tr-fatima', 's-f8', 0, 80, 'If the system could propose a new plan and I just approve it, that''s an hour back every single day', 'opportunity', 'Approve-a-replan AI concept', array['tag-planning','tag-ai']::text[], 'u-tom', 'in-plan-ai-opt')
on conflict (id) do nothing;

insert into public.kanban_boards (account_id, id, project_id, name, columns, cards) values
  ('acc_northwind', 'kb-triage', null, 'Insight Triage', '[{"id":"c-raw","title":"Raw Findings","accent":"slate"},{"id":"c-review","title":"Needs Review","accent":"amber"},{"id":"c-valid","title":"Validated","accent":"blue"},{"id":"c-opp","title":"Opportunity","accent":"violet"},{"id":"c-backlog","title":"Product Backlog","accent":"teal"},{"id":"c-done","title":"Completed","accent":"green"}]'::jsonb, '[{"id":"kc-1","columnId":"c-valid","title":"Connectivity loss drops work orders","insightId":"in-offline-sync","participantId":"pt-lukas","interviewId":"iv-lukas-1","tagIds":["tag-mobile-experience"],"assigneeId":"u-sanne"},{"id":"kc-2","columnId":"c-opp","title":"Offline-first with visible sync state","insightId":"in-mobile-offline-trust","tagIds":["tag-mobile-experience","tag-high-value"],"assigneeId":"u-julia"},{"id":"kc-3","columnId":"c-valid","title":"Global search unreliable across entities","insightId":"in-search-global","participantId":"pt-marie","tagIds":["tag-search"],"assigneeId":"u-sanne"},{"id":"kc-4","columnId":"c-opp","title":"AI proposes a re-plan to approve","insightId":"in-plan-ai-opt","participantId":"pt-fatima","tagIds":["tag-ai","tag-high-value"],"assigneeId":"u-lena"},{"id":"kc-5","columnId":"c-backlog","title":"Persist / save filters (quick win)","insightId":"in-search-recent","tagIds":["tag-quick-win"],"assigneeId":"u-lena"},{"id":"kc-6","columnId":"c-review","title":"Dashboard data-freshness signaling","insightId":"in-report-trust","participantId":"pt-james","tagIds":["tag-dashboards"],"assigneeId":"u-sanne"},{"id":"kc-7","columnId":"c-review","title":"KPI needs differ by persona","insightId":"in-report-kpi-persona","tagIds":["tag-reporting","tag-needs-validation"]},{"id":"kc-8","columnId":"c-raw","title":"Notification priority levels","insightId":"in-notif-noise","participantId":"pt-carlos","tagIds":["tag-notifications"]},{"id":"kc-9","columnId":"c-raw","title":"Real-time technician status","insightId":"in-plan-visibility","tagIds":["tag-needs-validation"]},{"id":"kc-10","columnId":"c-opp","title":"AI failure-pattern clustering","insightId":"in-ai-failure-pattern","participantId":"pt-priya","tagIds":["tag-ai"],"assigneeId":"u-tom"},{"id":"kc-11","columnId":"c-done","title":"Search quick wins shipped (Q1 study)","insightId":"in-stock-findability","tagIds":["tag-search"],"assigneeId":"u-sanne"},{"id":"kc-12","columnId":"c-backlog","title":"Guided first-run onboarding","insightId":"in-onboard-firstrun","tagIds":["tag-onboarding"],"assigneeId":"u-julia"}]'::jsonb),
  ('acc_northwind', 'kb-mobile', 'pr-mobile', 'Mobile Study Board', '[{"id":"c-raw","title":"Raw Findings","accent":"slate"},{"id":"c-review","title":"Needs Review","accent":"amber"},{"id":"c-valid","title":"Validated","accent":"blue"},{"id":"c-opp","title":"Opportunity","accent":"violet"},{"id":"c-backlog","title":"Product Backlog","accent":"teal"},{"id":"c-done","title":"Completed","accent":"green"}]'::jsonb, '[{"id":"kcm-1","columnId":"c-valid","title":"Session timeout during turbine climb","insightId":"in-offline-sync","participantId":"pt-lukas","interviewId":"iv-lukas-1","tagIds":["tag-performance"],"assigneeId":"u-sanne"},{"id":"kcm-2","columnId":"c-valid","title":"Sync uncertainty → screenshot workaround","insightId":"in-mobile-offline-trust","participantId":"pt-lukas","tagIds":["tag-mobile-experience"]},{"id":"kcm-3","columnId":"c-opp","title":"Offline-first mobile concept","insightId":"in-mobile-offline-trust","tagIds":["tag-high-value"],"assigneeId":"u-julia"},{"id":"kcm-4","columnId":"c-review","title":"Photo upload retries on weak signal","insightId":"in-mobile-photo","participantId":"pt-nadia","tagIds":["tag-performance"]},{"id":"kcm-5","columnId":"c-review","title":"Alert fatigue from flat notifications","insightId":"in-notif-noise","participantId":"pt-carlos","tagIds":["tag-notifications"]},{"id":"kcm-6","columnId":"c-raw","title":"Too many taps to start a job","insightId":"in-mobile-nav-depth","participantId":"pt-piet","tagIds":["tag-navigation"]},{"id":"kcm-7","columnId":"c-raw","title":"Asset search slower than the repair","insightId":"in-search-global","participantId":"pt-lukas","tagIds":["tag-search"]}]'::jsonb)
on conflict (id) do nothing;

insert into public.affinity_boards (account_id, id, project_id, name, groups, notes) values
  ('acc_northwind', 'af-mobile', 'pr-mobile', 'Mobile Study — Affinity Map', '[{"id":"ag-offline","title":"Offline & Sync","accent":"blue"},{"id":"ag-trust","title":"Trust & Confidence","accent":"violet"},{"id":"ag-find","title":"Findability","accent":"cyan"},{"id":"ag-notif","title":"Notifications","accent":"amber"},{"id":"ag-onboard","title":"Learnability (AI-suggested)","accent":"green","aiSuggested":true}]'::jsonb, '[{"id":"an-1","text":"App logs out during the climb; work order lost","kind":"pain-point","sourceParticipantId":"pt-lukas","groupId":"ag-offline"},{"id":"an-2","text":"No signal at pump stations — paper as offline bridge","kind":"pain-point","sourceParticipantId":"pt-thomas","groupId":"ag-offline"},{"id":"an-3","text":"Pages hang on the hospital ward","kind":"observation","sourceParticipantId":"pt-nadia","groupId":"ag-offline"},{"id":"an-4","text":"Never sure an update actually saved","kind":"insight","sourceParticipantId":"pt-lukas","groupId":"ag-trust"},{"id":"an-5","text":"Screenshots everything ''just in case''","kind":"observation","sourceParticipantId":"pt-lukas","groupId":"ag-trust"},{"id":"an-6","text":"Re-keys from paper to feel safe","kind":"observation","sourceParticipantId":"pt-thomas","groupId":"ag-trust"},{"id":"an-7","text":"Photographs nameplate instead of searching","kind":"pain-point","sourceParticipantId":"pt-lukas","groupId":"ag-find"},{"id":"an-8","text":"Search wants exact codes he doesn''t memorize","kind":"pain-point","sourceParticipantId":"pt-lukas","groupId":"ag-find"},{"id":"an-9","text":"Team swipes notifications away unread","kind":"pain-point","sourceParticipantId":"pt-carlos","groupId":"ag-notif"},{"id":"an-10","text":"Photo upload takes several retries","kind":"pain-point","sourceParticipantId":"pt-nadia","groupId":"ag-notif"},{"id":"an-11","text":"Paper never crashed — trust in reliability","kind":"insight","sourceParticipantId":"pt-piet","groupId":"ag-onboard"},{"id":"an-12","text":"Would adopt if the tool proved dependable","kind":"opportunity","sourceParticipantId":"pt-piet","groupId":"ag-onboard"},{"id":"an-13","text":"Offline-first would be ''huge'' with visible sync","kind":"opportunity","sourceParticipantId":"pt-lukas","groupId":null},{"id":"an-14","text":"Wants to know before starting what a job needs","kind":"user-need","sourceParticipantId":"pt-nadia","groupId":null}]'::jsonb)
on conflict (id) do nothing;
